### ISSUE TITLE
[Translations] - Simplified Chinese

### ISSUE THREAD

**Issue by jlooper** [microsoft/ML-For-Beginners#144]
- [x] Base README.md
- [ ] Quizzes
- [x] Introduction base README
   - [x] Intro to ML README
   - [x] Intro to ML assignment
   - [x] History of ML README
   - [x] History of ML assignment
   - [x] Fairness README
   - [x] Fairness assignment
   - [x] Techniques of ML README
   - [x] Techniques of ML assignment
- [x] Regression base README
   - [x] Tools README
   - [x] Tools assignment
   - [x] Data README
   - [x] Data assignment
   - [x] Linear README
   - [x] Linear assignment
   - [x] Logistic README
   - [x] Logistic assignment
- [ ] Web app base README
   - [x] Web app README
   - [x] Web app assignment
- [ ] Classification base README
   - [x] Intro README
   - [ ] Intro assignment
   - [ ] Classifiers 1 README
   - [ ] Classifiers 1  assignment
   - [ ] Classifiers 2  README
   - [ ] Classifiers 2  assignment
   - [ ] Applied README
   - [ ] Applied assignment
- [ ] Clustering base README
   - [ ] Visualize README
   - [ ] Visualize assignment
   - [ ] K-means README
   - [ ] K-means assignment
- [ ] NLP base README
   - [x] Intro README
   - [ ] Intro assignment
   - [ ] Tasks README
   - [ ] Tasks  assignment
   - [ ] Translation README
   - [ ] Translation  assignment
   - [ ] Reviews 1 README
   - [ ] Reviews 1 assignment
   - [ ] Reviews 2 README
   - [ ] Reviews 2 assignment
- [ ] Time Series base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] ARIMA README
   - [ ] ARIMA  assignment
- [x] Reinforcement base README
   - [ ] QLearning README
   - [ ] QLearning assignment
   - [ ] gym README
   - [ ] gym  assignment
- [x] Real World base README
   - [ ] Real World README
   - [ ] Real World assignment

**Comment by ChungZH** [comment]
I think we can follow this [guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines).
How about adding it to https://github.com/microsoft/ML-For-Beginners/blob/main/TRANSLATIONS.md ? @jlooper @feiyun0112

**Comment by mansijain980** [comment]
@jlooper Pls let me know Can i work on this issue ?
Assign it to me asap as I want  to contribute.

**Comment by ChungZH** [comment]
> @jlooper Pls let me know Can i work on this issue ?
> Assign it to me asap as I want to contribute.

Yes you can create PRs.

**Comment by mansijain980** [comment]
That's grt . Thanks

**Comment by SpokieKid** [comment]
> That's grt . Thanks

Would you be so kind as to explain how can I contribute to the translation?

**Comment by ChungZH** [comment]
@SpokieKid read this https://github.com/microsoft/ML-For-Beginners/blob/main/TRANSLATIONS.md

**Comment by SpokieKid** [comment]
@ChungZH Thanks, much appreciated.

**Comment by mansijain980** [comment]
@SpokieKid i m working on this issue . U can find some other issue to solve.

**Comment by SpokieKid** [comment]
@mansijain980 Got it, thanks for the headsup

**Comment by ChungZH** [comment]
I think everyone can contribute unless you can translate all.

**Comment by mansijain980** [comment]
Sure , I m working on Quizzes and clustering base readme .Except these @SpokieKid can contribute.

**Comment by mansijain980** [comment]
Clustering base README
 Visualize README
 Visualize assignment
 K-means README
 K-means assignment 
These 4 and quizzes.

**Comment by SpokieKid** [comment]
@mansijain980 That's a detailed list, thanks

**Comment by mansijain980** [comment]
@jlooper @ChungZH I have done quizzes .Please have a check on it and merge PR.

**Comment by Kaif2069** [comment]
Command not configured for CSS!

Add an [issue on GitHub](https://github.com/atom-ide-community/atom-script/issues/new?title=Add%20support%20for%20CSS) or send your own Pull Request.

I`m not getting the css part, just html is get executed 
can someone help! ( ;

**Comment by jlooper** [comment]
Not sure what the problem is, can you give more information, and try the Discussion boards?
