### ISSUE TITLE
[TRANSLATIONS] - Korean

### ISSUE THREAD

**Issue by jlooper** [microsoft/ML-For-Beginners#147]
- [ ] Base README.md
- [ ] Quizzes
- [ ] Introduction base README
   - [ ] Intro to ML README
   - [ ] Intro to ML assignment
   - [ ] History of ML README
   - [ ] History of ML assignment
   - [ ] Fairness README
   - [ ] Fairness assignment
   - [ ] Techniques of ML README
   - [ ] Techniques of ML assignment
- [ ] Regression base README
   - [ ] Tools README
   - [ ] Tools assignment
   - [ ] Data README
   - [ ] Data assignment
   - [ ] Linear README
   - [ ] Linear assignment
   - [ ] Logistic README
   - [ ] Logistic assignment
- [ ] Web app base README
   - [ ] Web app README
   - [ ] Web app assignment
- [ ] Classification base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Classifiers 1 README
   - [ ] Classifiers 1  assignment
   - [ ] Classifiers 2  README
   - [ ] Classifiers 2  assignment
   - [ ] Applied README
   - [ ] Applied assignment
- [ ] Clustering base README
   - [ ] Visualize README
   - [ ] Visualize assignment
   - [ ] K-means README
   - [ ] K-means assignment
- [ ] NLP base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Tasks README
   - [ ] Tasks  assignment
   - [ ] Translation README
   - [ ] Translation  assignment
   - [ ] Reviews 1 README
   - [ ] Reviews 1 assignment
   - [ ] Reviews 2 README
   - [ ] Reviews 2 assignment
- [ ] Time Series base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] ARIMA README
   - [ ] ARIMA  assignment
- [ ] Reinforcement base README
   - [ ] QLearning README
   - [ ] QLearning assignment
   - [ ] gym README
   - [ ] gym  assignment
- [ ] Real World base README
   - [ ] Real World README
   - [ ] Real World assignment

**Comment by mark7588** [comment]
If you need the translation of contents. I am down for helping you.
