### ISSUE TITLE
[TRANSLATIONS] - Portuguese

### ISSUE THREAD

**Issue by jlooper** [microsoft/ML-For-Beginners#148]
- [x] Base README.md
- [ ] Quizzes
- [ ] Introduction base README
   - [ ] Intro to ML README
   - [ ] Intro to ML assignment
   - [ ] History of ML README
   - [ ] History of ML assignment
   - [ ] Fairness README
   - [ ] Fairness assignment
   - [ ] Techniques of ML README
   - [ ] Techniques of ML assignment
- [ ] Regression base README
   - [ ] Tools README
   - [ ] Tools assignment
   - [ ] Data README
   - [ ] Data assignment
   - [ ] Linear README
   - [ ] Linear assignment
   - [ ] Logistic README
   - [ ] Logistic assignment
- [ ] Web app base README
   - [ ] Web app README
   - [ ] Web app assignment
- [ ] Classification base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Classifiers 1 README
   - [ ] Classifiers 1  assignment
   - [ ] Classifiers 2  README
   - [ ] Classifiers 2  assignment
   - [ ] Applied README
   - [ ] Applied assignment
- [ ] Clustering base README
   - [ ] Visualize README
   - [ ] Visualize assignment
   - [ ] K-means README
   - [ ] K-means assignment
- [ ] NLP base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Tasks README
   - [ ] Tasks  assignment
   - [ ] Translation README
   - [ ] Translation  assignment
   - [ ] Reviews 1 README
   - [ ] Reviews 1 assignment
   - [ ] Reviews 2 README
   - [ ] Reviews 2 assignment
- [ ] Time Series base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] ARIMA README
   - [ ] ARIMA  assignment
- [ ] Reinforcement base README
   - [ ] QLearning README
   - [ ] QLearning assignment
   - [ ] gym README
   - [ ] gym  assignment
- [ ] Real World base README
   - [ ] Real World README
   - [ ] Real World assignment

**Comment by hi-hi-ray** [comment]
Hi,
I'm Brazilian, can i help with this issue?

**Comment by jlooper** [comment]
Yes please! If you feel like we should differentiate between pt-br and pt-pt we can do that too. Maybe take a look at the work that's begun and see what you think?

**Comment by hi-hi-ray** [comment]
Yeah, we can totally differentiate the portugueses, because we have some different ways to write some words. =]

**Comment by jlooper** [comment]
sounds like a good idea, why don't you create a draft PR for pt-br and add a checklist that you can manage as an issue, we'll keep this one for pt-pt, sound ok?

**Comment by Nockkk** [comment]
Hello,
I am Portuguese. If you want, I can work on this issue. I can translate to pt-pt.

**Comment by claire-me** [comment]
Heyy @jlooper, can I take on one of these?

**Comment by jlooper** [comment]
hi! let's gather on the discussion boards and maybe you can divide the work together! thanks! Obrigado!

**Comment by hi-hi-ray** [comment]
If someone wants to help with the PT-BR translation, fell free also to tag me. =]

**Comment by annemacena** [comment]
Hey everyone, if you wanted help with translating pt-br stuff, i'm in @hi-hi-ray @jlooper

**Comment by hi-hi-ray** [comment]
Hi! @annemacena! Choose the files that you want to translate and create a PR draft of them with a checklist. =]

The following files are already translated. =]
- Base README.md
- Quizzes
- Introduction base README
-    Intro to ML README
-    Intro to ML assignment
-    History of ML README
-    History of ML assignment
-    Fairness README
-    Fairness assignment
-    Techniques of ML README
-    Techniques of ML assignment

**Comment by fernandakawasaki** [comment]
Hi, I would like to help translate to pt-br too! I will start working on the section NLP base

**Comment by tamesps** [comment]
Hi! I can help translate the Clustering section to pt-br.

**Comment by hi-hi-ray** [comment]
@tamesps  Go for it!! If you need any help, feel free to ask. =]

**Comment by annemacena** [comment]
FYI

* [x]  Base README.md
* [x]  Quizzes
* [x]  Introduction base README
* [x]  Regression base README
* [x]  Web app base README
* [ ]  Classification base README
* [ ]  Clustering base README (@tamesps)
* [x]  NLP base README
* [ ]  Time Series base README
* [ ]  Reinforcement base README
* [ ]  Real World base README

**Comment by annemacena** [comment]
Also, I'm taking "Classification base" section for now 👩‍❤️‍💋‍👩
