### ISSUE TITLE
[TRANSLATIONS] - Turkish

### ISSUE THREAD

**Issue by emrecgty** [microsoft/ML-For-Beginners#153]
- [x] Base README.md
- [x] Quizzes
- [ ] Introduction base README
   - [x] Intro to ML README
   - [x] Intro to ML assignment
   - [x] History of ML README
   - [x] History of ML assignment
   - [ ] Fairness README
   - [ ] Fairness assignment
   - [ ] Techniques of ML README
   - [ ] Techniques of ML assignment
- [ ] Regression base README
   - [ ] Tools README
   - [ ] Tools assignment
   - [ ] Data README
   - [ ] Data assignment
   - [ ] Linear README
   - [ ] Linear assignment
   - [ ] Logistic README
   - [ ] Logistic assignment
- [ ] Web app base README
   - [ ] Web app README
   - [ ] Web app assignment
- [x] Classification base README
   - [x] Intro README
   - [x] Intro assignment
   - [x] Classifiers 1 README
   - [x] Classifiers 1  assignment
   - [x] Classifiers 2  README
   - [x] Classifiers 2  assignment
   - [x] Applied README
   - [x] Applied assignment
- [ ] Clustering base README
   - [ ] Visualize README
   - [ ] Visualize assignment
   - [ ] K-means README
   - [ ] K-means assignment
- [ ] NLP base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Tasks README
   - [ ] Tasks  assignment
   - [ ] Translation README
   - [ ] Translation  assignment
   - [ ] Reviews 1 README
   - [ ] Reviews 1 assignment
   - [ ] Reviews 2 README
   - [ ] Reviews 2 assignment
- [ ] Time Series base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] ARIMA README
   - [ ] ARIMA  assignment
- [ ] Reinforcement base README
   - [ ] QLearning README
   - [ ] QLearning assignment
   - [ ] gym README
   - [ ] gym  assignment
- [ ] Real World base README
   - [ ] Real World README
   - [ ] Real World assignment

**Comment by emrecgty** [comment]
#152 Adds Turkish translation of quiz-app

**Comment by emrecgty** [comment]
#154 Adds Turkish translation of "Intro to ML" and "History of ML", fixes an issue with the translation of the quiz-app

**Comment by buseorak** [comment]
Greetings @emrecgty! I would love to join you and work together on the Turkish translation, if it is okay for you too.

**Comment by emrecgty** [comment]
@buseorak of course! Any and all help is welcome 🙌

**Comment by buseorak** [comment]
I will be working on the base README.md and files under Classification if they are not already assigned. :)

**Comment by jlooper** [comment]
Since quizzes are done you can now link to them with the parameter ?loc=tr
