### ISSUE TITLE
[TRANSLATIONS] - French

### ISSUE THREAD

**Issue by ManuSquall** [microsoft/ML-For-Beginners#166]
- [ ] Base README.md
- [x] Quizzes
- [x] Introduction base README
   - [x] Intro to ML README
   - [x] Intro to ML assignment
   - [x] History of ML README (Doing: @simplg )
   - [x] History of ML assignment (Doing: @simplg )
   - [x] Fairness README
   - [x] Fairness assignment
   - [ ] Techniques of ML README
   - [ ] Techniques of ML assignment
- [x] Regression base README
   - [ ] Tools README
   - [ ] Tools assignment
   - [ ] Data README
   - [ ] Data assignment
   - [ ] Linear README
   - [ ] Linear assignment
   - [ ] Logistic README
   - [ ] Logistic assignment
- [ ] Web app base README
   - [ ] Web app README
   - [ ] Web app assignment
- [ ] Classification base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Classifiers 1 README
   - [ ] Classifiers 1  assignment
   - [ ] Classifiers 2  README
   - [ ] Classifiers 2  assignment
   - [ ] Applied README
   - [ ] Applied assignment
- [ ] Clustering base README
   - [ ] Visualize README
   - [ ] Visualize assignment
   - [ ] K-means README
   - [ ] K-means assignment
- [ ] NLP base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Tasks README
   - [ ] Tasks  assignment
   - [ ] Translation README
   - [ ] Translation  assignment
   - [ ] Reviews 1 README
   - [ ] Reviews 1 assignment
   - [ ] Reviews 2 README
   - [ ] Reviews 2 assignment
- [ ] Time Series base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] ARIMA README
   - [ ] ARIMA  assignment
- [ ] Reinforcement base README
   - [ ] QLearning README
   - [ ] QLearning assignment
   - [ ] gym README
   - [ ] gym  assignment
- [ ] Real World base README
   - [ ] Real World README
   - [ ] Real World assignment

**Comment by simplg** [comment]
I've started a discussion group so we can move the discussion on how to cooperate there #186

**Comment by Zxce3** [comment]
I want to do it also in Indonesian

**Comment by ManuSquall** [comment]
A Translation group discussion @Zxce3 ?

**Comment by Zxce3** [comment]
Yes

**Comment by Zxce3** [comment]
> A Translation group discussion @Zxce3 ?

Yes

**Comment by ManuSquall** [comment]
You can create one on discussion tab:
![image](https://user-images.githubusercontent.com/29026887/126022893-2cf70083-7d45-4bb1-8966-2d998b7b041c.png)

**Comment by Zxce3** [comment]
> You can create one on discussion tab:
> ![image](https://user-images.githubusercontent.com/29026887/126022893-2cf70083-7d45-4bb1-8966-2d998b7b041c.png)
> 

Alright, thank you very much
