### ISSUE TITLE
CSV file like is not given

### ISSUE THREAD

**Issue by naazkakria** [microsoft/ML-For-Beginners#179]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jlooper** [comment]
Can you explain what the issue is, and where?

**Comment by naazkakria** [comment]
link for downloading cuisine data set is not given
df  = pd.read_csv('../data/cuisines.csv')

**Comment by jlooper** [comment]
hi, please reference the file - you can also PR this repo with a fix

**Comment by emrecgty** [comment]
Cuisine dataset with the [`"cuisines.csv"`](https://github.com/microsoft/ML-For-Beginners/blob/main/4-Classification/data/cuisines.csv) file name is referenced in [the first lesson of classification](https://github.com/microsoft/ML-For-Beginners/blob/main/4-Classification/1-Introduction/README.md#exercise---clean-and-balance-your-data). This dataset need not be downloaded from an external source as it is included in the data folder. 

- If you've cloned the repo, you should work with the included "notebook.ipynb" file and should not experience any problem with the code that you have referenced. 
- If you did not clone the repo or if you are working with a notebook in a separate directory of your own, make sure to 
    - download it from [here](https://github.com/microsoft/ML-For-Beginners/blob/main/4-Classification/data/cuisines.csv)
    - and change the file path `"../data/cuisines.csv"` according to the new relative path.
