### ISSUE TITLE
[EDITION]: R Edition

### ISSUE THREAD

**Issue by jlooper** [microsoft/ML-For-Beginners#194]
Proposal to create R versions of all solutions as appropriate:

- [ ] Base README-R.md - About R (An introductory lesson)
- [x] Regression: Tools
- [x] Regression: Data
- [x] Regression: Linear
- [x] Regression: Logistic
- [x] Classification: Classifiers 1
- [x] Classification: Classifiers 2
- [x] Clustering: Visualize
- [x] Clustering: K-means
- [ ] NLP: Sentiment
- [ ] Time Series: Intro

**Comment by jlooper** [comment]
@R-icntay

**Comment by ravindranath-sawane** [comment]
oK, I will try to add as many R versions as I can.. @jlooper

**Comment by jlooper** [comment]
hi @ravindranath-sawane - @R-icntay is leading this but I'd recommend chatting with him on the bulletin boards. I'll create a thread for you!

**Comment by ravindranath-sawane** [comment]
Okay, @jlooper. Definitely, we will do it together @R-icntay

**Comment by Shujasheikh** [comment]
@R
