### ISSUE TITLE
Missing comma inside 4.1 Introduction to classification

### ISSUE THREAD

**Issue by simplg** [microsoft/ML-For-Beginners#208]
**Describe the bug**
SyntaxError: invalid syntax (Temp/ipykernel_2488/1822953119.py, line 5)
  File "C:\Users\demon\AppData\Local\Temp/ipykernel_2488/1822953119.py", line 5
    inplace=False)
    ^
SyntaxError: invalid syntax

**To Reproduce**
Run create_ingredient function definition from (https://github.com/microsoft/ML-For-Beginners/blob/main/4-Classification/1-Introduction/README.md#discovering-ingredients):
```python
def create_ingredient_df(df):
    ingredient_df = df.T.drop(['cuisine','Unnamed: 0']).sum(axis=1).to_frame('value')
    ingredient_df = ingredient_df[(ingredient_df.T != 0).any()]
    ingredient_df = ingredient_df.sort_values(by='value', ascending=False
    inplace=False)
    return ingredient_df
```

**Expected behavior**
Should define a function without errors

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IDE: VS Code

**Additional context**
The fix is easy, there is a missing comma just after `ascending=False`. Adding it back fix the problem!

**Comment by jlooper** [comment]
You can PR this please, also let’s check the solution to ensure it’s correct there
