### ISSUE TITLE
Wrong import in 4.2 classification 1

### ISSUE THREAD

**Issue by simplg** [microsoft/ML-For-Beginners#209]
**Describe the bug**
FileNotFoundError: [Errno 2] No such file or directory: '../../data/cleaned_cuisine.csv'

**To Reproduce**
Execute the first cell of https://github.com/microsoft/ML-For-Beginners/blob/main/4-Classification/2-Classifiers-1/README.md .

**Expected behavior**
The cell should be executable and should import a csv file created previously in 4.1

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
In the previous course, we have created the file to this path: "../data/cleaned_cuisine.csv". It seems like the path is wrong here with an extra "../". Putting the correct path "../data/cleaned_cuisine.csv" fixes the problem.

**Comment by jlooper** [comment]
Thanks, you can PR this fix- 👍🙏
