### ISSUE TITLE
Incorrect web app folder structure in 3-Web-App/1-Web-App's Chinese README.md

### ISSUE THREAD

**Issue by kirisamemarisaa** [microsoft/ML-For-Beginners#233]
**Describe the bug**
The Web App folder structure in `ML-For-Beginners/3-Web-App/1-Web-App/translations/`'s `README.md` (Chinese ver.) is incorrect.

**Expected behavior**
Folder `templates/` should share the same depth with `static/`, not being its subfolder.
```
web-app/
  static/
    css/
  templates/
notebook.ipynb
ufo-model.pkl
```

**Screenshots**
(This screenshot shows that the current folder structure is incorrect)
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/60131395/126884790-449d6940-2c6c-4faf-a97b-fffe11735c3e.png">

(This screenshot shows the correct folder structure)
<img width="296" alt="image" src="https://user-images.githubusercontent.com/60131395/126884732-0b88e0d7-ee78-4691-a9b9-77667f83beb7.png">

**Comment by jlooper** [comment]
thank you, fixed it. Feel free to PR the repo!
