### ISSUE TITLE
Lesson 5 notebook is blank

### ISSUE THREAD

**Issue by Davidy22** [microsoft/ML-For-Beginners#295]
**Describe the bug**
The notebook for the first lesson in regression is blank

**To Reproduce**
Open the notebook in regression->tools

**Expected behavior**
A notebook with content

**Desktop (please complete the following information):**
 - OS: Mint
 - Browser Firefox
 - Version Latest

**Comment by jlooper** [comment]
That's the working notebook, that you start with and populate by following the lesson. The solution is in the 'solution' folder.

**Comment by Davidy22** [comment]
Oh whoops, misread the lesson, thought it was going to have something in it.
