### ISSUE TITLE
System setup for the ML course

### ISSUE THREAD

**Issue by alfredodeza** [microsoft/ML-For-Beginners#302]
### Discussed in https://github.com/microsoft/ML-For-Beginners/discussions/252

<div type='discussions-op-text'>

<sup>Originally posted by **cjd2003** July 30, 2021</sup>
Hi,
In order to configure my system for this course, I tried clicking the link in the first lesson 1 - Into_to _ML but it took me to a set of videos for "Introduction to Python".. I was wondering if I could get the correct link. 

Thank you.
</div>

**Comment by ravindranath-sawane** [comment]
All the links are correct as I can see...  Can you specify exactly which link is Wrong.

**Comment by alfredodeza** [comment]
> All the links are correct as I can see... Can you specify exactly which link is Wrong.

@ravindranath-sawane see my comments on #252 and the corresponding PR with a proposed fix at #304
