### ISSUE TITLE
Adding Blog Management Facility

### ISSUE THREAD

**Issue by mansijain980** [microsoft/ML-For-Beginners#326]
If I want to add something related to ML. thoughts etc . I can't find it . This is helpful for interaction as well.

**Description
It would be interesting if anyone can post their ideas , their thoughts somewhere regarding this Quiz-app or anything about ML.
I want to add this blog management feature in this .

Please let me know if it sounds great to you or not.
Thnaks.
@jlooper

**Comment by jlooper** [comment]
We have the discussion boards for this
