### ISSUE TITLE
[TRANSLATIONS]

### ISSUE THREAD

**Issue by likeremix715** [microsoft/ML-For-Beginners#337]
- [x] Base README.md
- [x] Quizzes
- [x] Introduction base README
   - [x] Intro to ML README
   - [x] Intro to ML assignment
   - [x] History of ML README
   - [x] History of ML assignment
   - [x] Fairness README
   - [x] Fairness assignment
   - [x] Techniques of ML README
   - [x] Techniques of ML assignment
- [x] Regression base README
   - [x] Tools README
   - [x] Tools assignment
   - [x] Data README
   - [x] Data assignment
   - [x] Linear README
   - [x] Linear assignment
   - [ ] Logistic README
   - [ ] Logistic assignment
- [ ] Web app base README
   - [ ] Web app README
   - [ ] Web app assignment
- [ ] Classification base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Classifiers 1 README
   - [ ] Classifiers 1  assignment
   - [ ] Classifiers 2  README
   - [ ] Classifiers 2  assignment
   - [ ] Applied README
   - [ ] Applied assignment
- [ ] Clustering base README
   - [ ] Visualize README
   - [ ] Visualize assignment
   - [ ] K-means README
   - [ ] K-means assignment
- [ ] NLP base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Tasks README
   - [ ] Tasks  assignment
   - [ ] Translation README
   - [ ] Translation  assignment
   - [ ] Reviews 1 README
   - [ ] Reviews 1 assignment
   - [ ] Reviews 2 README
   - [ ] Reviews 2 assignment
- [x] Time Series base README
   - [x] Intro README
   - [x] Intro assignment
   - [x] ARIMA README
   - [x] ARIMA  assignment
- [x] Reinforcement base README
   - [x] QLearning README
   - [x] QLearning assignment
   - [x] gym README
   - [x] gym  assignment
- [x] Real World base README
   - [x] Real World README
   - [x] Real World assignment

**Comment by jlooper** [comment]
What language is this for?

**Comment by likeremix715** [comment]
> - [x] Base README.md
> - [x] Quizzes
> - [x] Introduction base README
>    - [x] Intro to ML README
>    - [x] Intro to ML assignment
>    - [x] History of ML README
>    - [x] History of ML assignment
>    - [x] Fairness README
>    - [x] Fairness assignment
>    - [x] Techniques of ML README
>    - [x] Techniques of ML assignment
> - [x] Regression base README
>    - [x] Tools README
>    - [x] Tools assignment
>    - [x] Data README
>    - [x] Data assignment
>    - [x] Linear README
>    - [x] Linear assignment
>    - [ ] Logistic README
>    - [ ] Logistic assignment
> - [ ] Web app base README
>    - [ ] Web app README
>    - [ ] Web app assignment
> - [ ] Classification base README
>    - [ ] Intro README
>    - [ ] Intro assignment
>    - [x] Classifiers 1 README
>    - [ ] Classifiers 1  assignment
>    - [ ] Classifiers 2  README
>    - [ ] Classifiers 2  assignment
>    - [ ] Applied README
>    - [ ] Applied assignment
> - [ ] Clustering base README
>    - [ ] Visualize README
>    - [ ] Visualize assignment
>    - [ ] K-means README
>    - [ ] K-means assignment
> - [ ] NLP base README
>    - [ ] Intro README
>    - [ ] Intro assignment
>    - [ ] Tasks README
>    - [ ] Tasks  assignment
>    - [ ] Translation README
>    - [ ] Translation  assignment
>    - [ ] Reviews 1 README
>    - [ ] Reviews 1 assignment
>    - [ ] Reviews 2 README
>    - [ ] Reviews 2 assignment
> - [x] Time Series base README
>    - [x] Intro README
>    - [x] Intro assignment
>    - [x] ARIMA README
>    - [x] ARIMA  assignment
> - [x] Reinforcement base README
>    - [x] QLearning README
>    - [x] QLearning assignment
>    - [x] gym README
>    - [x] gym  assignment
> - [x] Real World base README
>    - [x] Real World README
>    - [x] Real World assignment
