### ISSUE TITLE
[TRANSLATIONS]

### ISSUE THREAD

**Issue by Flozile** [microsoft/ML-For-Beginners#345]
- [x] Base README.md
- [x] Quizzes
- [x] Introduction base README
   - [ ] Intro to ML README
   - [ ] Intro to ML assignment
   - [ ] History of ML README
   - [ ] History of ML assignment
   - [ ] Fairness README
   - [ ] Fairness assignment
   - [ ] Techniques of ML README
   - [ ] Techniques of ML assignment
- [x] Regression base README
   - [ ] Tools README
   - [ ] Tools assignment
   - [ ] Data README
   - [ ] Data assignment
   - [ ] Linear README
   - [ ] Linear assignment
   - [ ] Logistic README
   - [ ] Logistic assignment
- [x] Web app base README
   - [ ] Web app README
   - [ ] Web app assignment
- [x] Classification base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [x] Classifiers 1 README
   - [x] Classifiers 1  assignment
   - [x] Classifiers 2  README
   - [x] Classifiers 2  assignment
   - [x] Applied README
   - [x] Applied assignment
- [x] Clustering base README
   - [x] Visualize README
   - [x] Visualize assignment
   - [x] K-means README
   - [x] K-means assignment
- [x] NLP base README
   - [x] Intro README
   - [x] Intro assignment
   - [x] Tasks README
   - [x] Tasks  assignment
   - [x] Translation README
   - [x] Translation  assignment
   - [x] Reviews 1 README
   - [x] Reviews 1 assignment
   - [x] Reviews 2 README
   - [x] Reviews 2 assignment
- [x] Time Series base README
   - [x] Intro README
   - [x] Intro assignment
   - [x] ARIMA README
   - [x] ARIMA  assignment
- [x] Reinforcement base README
   - [x] QLearning README
   - [x] QLearning assignment
   - [x] gym README
   - [x] gym  assignment
- [x] Real World base README
   - [x] Real World README
   - [x] Real World assignment

**Comment by jlooper** [comment]
for what language? Please only use this template for a given language translation suite of work

**Comment by Flozile** [comment]
https://github.com/microsoft/ML-For-Beginners/issues/343#issue-995279251
