### ISSUE TITLE
Joining the team 

### ISSUE THREAD

**Issue by Sharma0111** [microsoft/ML-For-Beginners#349]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Zippy-Pach** [comment]
Hi, thanks for the response.

What I mean to say is that yesterday I purchased Pro from your site and it
charged Rs1750. I thought it is for Lifetime but it is written that it will
be end on Next Year i.e 14/september/2022. If you guys can refund I'll be
very grateful. I want the Lifetime version not 1 year. I promise, I'll
surely buy again if you guys can do a refund. THANKS 😊👍
