### ISSUE TITLE
Pre & Post lecture quiz Links

### ISSUE THREAD

**Issue by datasiastic** [microsoft/ML-For-Beginners#356]
**Describe the bug**
The Link to the Pre and Post lectures won't work after i forked the repo or work on it locally .

**To Reproduce**
1. Go to 'any chapter'
2. Click on ' the lesson'
3. Scroll down to ' the Pre-lecture quiz'

**Expected behavior**
I expected that a tab will open so i can procced to answer the question.
![2021-09-17](https://user-images.githubusercontent.com/73499171/133855112-9bf850c3-5b24-4f3e-82c4-efb3774dda4c.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Browser [e.g. chrome ]
 - Version [e.g. 93]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jlooper** [comment]
hi, thank you for this bug report. Recently, I had to change the link for the quiz app, so the new one is this: https://white-water-09ec41f0f.azurestaticapps.net/quiz/1/

It's been updated in this repo, so you can either:

- edit your own repo to replace the other link with this new one 
or
- refresh your fork to update your version, after which the new links will be in place.

**Comment by datasiastic** [comment]
Ok I'll do that. Thank you @jlooper
