### ISSUE TITLE
The link https://microsoft.github.io/ML-For-Beginners/#/pdf returns 404 error

### ISSUE THREAD

**Issue by appauldev** [microsoft/ML-For-Beginners#357]
**Describe the bug**
The [github.io](https://microsoft.github.io/ML-For-Beginners/#/pdf) link for the PDF file of the curriculum is broken.

**To Reproduce**
1. Go to [https://microsoft.github.io/ML-For-Beginners](https://microsoft.github.io/ML-For-Beginners)
2. Open the hamburger menu and click 'PDFs', or scroll down to the PDFs section.
3. Click the link for the PDF file of the curriculum.
4. User will be directed to a `404 - Not Found` page.

**Expected behavior**
The user should be redirected to the PDF file of the curriculum instead of being redirected to a 404 Error page. ~~Changing the link to [https://github.com/microsoft/ML-For-Beginners/blob/main/pdf/readme.pdf](https://github.com/microsoft/ML-For-Beginners/blob/main/pdf/readme.pdf) might solve the issue.~~

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version: LVL3 (core: 78.0.4093.186)

**Comment by vishvanathan-k** [comment]
It need to point to https://microsoft.github.io/ML-For-Beginners/pdf/readme.pdf instead of https://microsoft.github.io/ML-For-Beginners/#/pdf/readme.pdf (this url returns 404 error).

**Comment by jlooper** [comment]
> It need to point to https://microsoft.github.io/ML-For-Beginners/pdf/readme.pdf instead of https://microsoft.github.io/ML-For-Beginners/#/pdf/readme.pdf (this url returns 404 error).

This is the diagnosis of the problem, you're right. If someone can figure out how to make this work with Docsify and relative paths I'm happy to accept a PR!

**Comment by vishvanathan-k** [comment]
@jlooper It seems using Docsify, you can't serve anything outside of docs folder, That's the reason why its not working. 
We need to change structure of the current file tree to correct it. Either we move the pdf to `docs/`  or  copy the readme.md and pdf to `docs/` and change the readme inside the folder to point to the pdf.
What way do you prefer ??

**Comment by jlooper** [comment]
> @jlooper It seems using Docsify, you can't serve anything outside of docs folder, That's the reason why its not working.
> We need to change structure of the current file tree to correct it. Either we move the pdf to `docs/` or copy the readme.md and pdf to `docs/` and change the readme inside the folder to point to the pdf.
> What way do you prefer ??

I read the same GH issue :) - I am thinking we can move the /pdf folder into /docs. We just must make a few link changes then and edit the path where the pdf is generated. Should work ok! thanks

**Comment by appauldev** [comment]
For those who are waiting for the official fix, you can try changing the PDF link in `README.md` with an HTML link, i.e., 
```
### PDF
Find a pdf of the curriculum with links <a href="pdf/readme.pdf">here.</a>
```

It's currently working as intended on both my local docsify copy and [github page copy](https://appauldev.github.io/ML-For-Beginners/#/?id=pdfs), but this is generally **not recommended** since this might cause site maintainability issues.

**Comment by Bossk67890** [comment]
Please stop sending me this
