### ISSUE TITLE
[TRANSLATIONS] - Spanish: Missing translations

### ISSUE THREAD

**Issue by hereje** [microsoft/ML-For-Beginners#411]
Even though the translated files exists, they are empty, as you can notice running the following command in your local repo.

```bash
find . -type f  -empty -name "*.es.md" | sort -n
```

- [ ] Base README.md
- [ ] Quizzes
- [x] Introduction base README
   - [x] Intro to ML README
   - [x] Intro to ML assignment
   - [x] History of ML README
   - [x] History of ML assignment
   - [x] Fairness README
   - [x] Fairness assignment
   - [x] Techniques of ML README
   - [x] Techniques of ML assignment
- [x] Regression base README
   - [x] Tools README
   - [x] Tools assignment
   - [ ] Data README
   - [x] Data assignment
   - [ ] Linear README
   - [x] Linear assignment
   - [ ] Logistic README
   - [ ] Logistic assignment
- [ ] Web app base README
   - [ ] Web app README
   - [ ] Web app assignment
- [x] Classification base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Classifiers 1 README
   - [ ] Classifiers 1  assignment
   - [ ] Classifiers 2  README
   - [ ] Classifiers 2  assignment
   - [ ] Applied README
   - [ ] Applied assignment
- [ ] Clustering base README (#472 )
   - [ ] Visualize README
   - [ ] Visualize assignment
   - [ ] K-means README
   - [ ] K-means assignment
- [ ] NLP base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Tasks README
   - [ ] Tasks  assignment
   - [ ] Translation README
   - [ ] Translation  assignment
   - [ ] Reviews 1 README
   - [ ] Reviews 1 assignment
   - [ ] Reviews 2 README
   - [ ] Reviews 2 assignment
- [ ] Time Series base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] ARIMA README
   - [ ] ARIMA  assignment
- [ ] Reinforcement base README
   - [ ] QLearning README
   - [ ] QLearning assignment
   - [ ] gym README
   - [ ] gym  assignment
- [x] Real World base README
   - [ ] Real World README
   - [x] Real World assignment

**Comment by jlooper** [comment]
oh yes, please do! re-opening, I misunderstood. thanks!

**Comment by Carlosbogo** [comment]
Hi! I saw that some people are already working on this, is there still anything I can help with?

**Comment by jlooper** [comment]
hi @Carlosbogo  @hereje and @FernandoRoldan93 and @yili001 you can create a discussion board group if it makes the work allocations easier

**Comment by Carlosbogo** [comment]
Would it be better to create a PR for each file I update to keep things organised and easier to check or should I just push all of them together in a single PR?

**Comment by jlooper** [comment]
> Would it be better to create a PR for each file I update to keep things organised and easier to check or should I just push all of them together in a single PR?

I recommend making a draft PR of several files together and then ask for a review

**Comment by abdull6771** [comment]
Thank you sir
