### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by munira8i** [microsoft/ML-For-Beginners#453]
create a class movie with the following instance variable and methods. instance variables : title ( string ) ,rating (int) . constructors: movie(string title , int ratings) ,Movie ( Movie movie ). methods:getTitle(),getRarings(),setTitle(),setRatings(),getCategroy(). For setRating(),the user must input rating between 0 and 10 . For getCategroy, it is a methods that return character such that: A : rating is equal to 9 or 10 B : rating is equal to 7 or 8 C : rating is equal to 5 or 6 D : rating is equal to 4 or 3 F : otherwise, Write the main program for variables and methods declaration.

**Comment by jlooper** [comment]
this belongs on discussion boards, properly contextualized as a PAT
