### ISSUE TITLE
Add detailed code explanations into notebook solutions

### ISSUE THREAD

**Issue by jlooper** [microsoft/ML-For-Beginners#454]
Our partner schools who are delivering this content need to be able to explain exactly what the code is doing, and to that end, we should add very good explanations of the code itself in the lessons. 

- [ ] Regression
- [ ] Clustering
- [ ] Classification
- [ ] Time Series
- [ ] NLP
- [ ] Reinforcement

**Comment by Huntershola** [comment]
[]()
