### ISSUE TITLE
R if in for loop error - how can I save selected model?

### ISSUE THREAD

**Issue by TomJang** [microsoft/ML-For-Beginners#539]
I am new to R and have difficulties using "if" and "for-loop". sorry if it is duplicated.

as you can see a chuck of a code below, I try to create 100 lm models and save when the R is more than 0.7.

However, the code saved all 100 lm models.

I suspect the statement (!is.na(lm.cv.r[i]) < 0.60) is wrong but I cannot figure it out.

let's use USArrests data as an example

``
      data("USArrests")
      head(USArrests)
      df.norm <- USArrests
    
    set.seed(100)
    lm.cv.mse <- NULL
    lm.cv.r <- NULL
    k <- 100

    for(i in 1:k){
    
    index.cv <- sample(1:nrow(df.norm),round(0.8*nrow(df.norm)))
    df.cv.train <- df.norm[index.cv, ]
    df.cv.test <- df.norm[-index.cv, ]
    
    lm.cv <- glm(Rape~., data = df.cv.train) 
    
    lm.cv.predicted <- predict(lm.cv, df.cv.test)
    
    lm.cv.mse[i] <- sum((df.cv.test$target - lm.cv.predicted)^2)/nrow(df.cv.test)
    lm.cv.r[i] <- as.numeric(round(cor(lm.cv.predicted, df.cv.test$target, method = "pearson"), digits = 3))
    
   
    if (!is.na(lm.cv.r[i]) > 0.70){
      saveRDS(lm.cv, file = paste("lm.cv", lm.cv.r[i], ".rds", sep = ''))
    }
}
``

**Comment by jlooper** [comment]
hi @R-icntay could you lend your expertise here please?

**Comment by TomJang** [comment]
Thanks Eric,

Apologies for the hassle with a tiny mistake. It took me a lot of time to figure it out!

Kind regards,
Tom

**Comment by jlooper** [comment]
all set? should I close this? thanks everyone!

**Comment by R-icntay** [comment]
Yes yes Jen. 

All good here!
