### ISSUE TITLE
[TRANSLATIONS] Hindi

### ISSUE THREAD

**Issue by iamrahulmahato** [microsoft/ML-For-Beginners#551]
- [x] Base README.md
- [ ] Quizzes
- [ ] Introduction base README
   - [ ] Intro to ML README
   - [ ] Intro to ML assignment
   - [ ] History of ML README
   - [ ] History of ML assignment
   - [ ] Fairness README
   - [ ] Fairness assignment
   - [ ] Techniques of ML README
   - [ ] Techniques of ML assignment
- [ ] Regression base README
   - [ ] Tools README
   - [ ] Tools assignment
   - [ ] Data README
   - [ ] Data assignment
   - [ ] Linear README
   - [ ] Linear assignment
   - [ ] Logistic README
   - [ ] Logistic assignment
- [ ] Web app base README
   - [ ] Web app README
   - [ ] Web app assignment
- [ ] Classification base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Classifiers 1 README
   - [ ] Classifiers 1  assignment
   - [ ] Classifiers 2  README
   - [ ] Classifiers 2  assignment
   - [ ] Applied README
   - [ ] Applied assignment
- [x] Clustering base README
   - [ ] Visualize README
   - [ ] Visualize assignment
   - [ ] K-means README
   - [ ] K-means assignment
- [ ] NLP base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Tasks README
   - [ ] Tasks  assignment
   - [ ] Translation README
   - [ ] Translation  assignment
   - [ ] Reviews 1 README
   - [ ] Reviews 1 assignment
   - [ ] Reviews 2 README
   - [ ] Reviews 2 assignment
- [ ] Time Series base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] ARIMA README
   - [ ] ARIMA  assignment
- [ ] Reinforcement base README
   - [ ] QLearning README
   - [ ] QLearning assignment
   - [ ] gym README
   - [ ] gym  assignment
- [ ] Real World base README
   - [ ] Real World README
   - [ ] Real World assignment

**Comment by iamrahulmahato** [comment]
@TemiTolu yes bro you can make another request for French and start working

**Comment by jlooper** [comment]
Before starting any translations, please look in the translation folder of each lesson, as it's likely the translations are already complete. We also have translator groups on our Discussion boards, so please check in there as well. Thanks!

**Comment by iamrahulmahato** [comment]
@jlooper ok i will do that

**Comment by Priyanshu-Singhz** [comment]
Hi, I am Priyanshu Singh, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by Priyanshu-Singhz** [comment]
Can anyone guide me ?

**Comment by jlooper** [comment]
> Before starting any translations, please look in the translation folder of each lesson, as it's likely the translations are already complete. We also have translator groups on our Discussion boards, so please check in there as well. Thanks!

Before starting any translations, please look in the translation folder of each lesson, as it's likely the translations are already complete. We also have translator groups on our Discussion boards, so please check in there as well. Thanks!

**Comment by TemiTolu** [comment]
Hello. 

I am trying to click on the Translation READ ME file to see all that has been done so far but it isn't responding. Am I doing it the right way please?

I'd love some guidance. 

Thank you.

**Comment by jlooper** [comment]
> Hello.
> 
> I am trying to click on the Translation READ ME file to see all that has been done so far but it isn't responding. Am I doing it the right way please?
> 
> I'd love some guidance.
> 
> Thank you.

you need to dig into the translation folders embedded in all the lessons to figure out what needs doing.

**Comment by iamrahulmahato** [comment]
@TemiTolu open the folder [translations](https://github.com/microsoft/ML-For-Beginners/tree/main/translations) you will see all the translations

**Comment by jlooper** [comment]
Please folks doing translations, make sure there are no dead links or missing images in your files, check your paths. Also all translations need to pass a human review, so please work together on the Discussion boards to make sure your translation is high quality. thanks!

**Comment by iamrahulmahato** [comment]
@jlooper thanks mam I will take care of it.
the issue is solved please review

**Comment by pao0318** [comment]
Hey ! I am Siddharth Sharma, I would like to work on this issue. Thankyou

**Comment by jlooper** [comment]
there's a new discussion group for linguistic review on the DB

**Comment by Aaditya-Singh78** [comment]
Hi, I am Aaditya Singh, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by jlooper** [comment]
I would like everyone here to go to the discussion group that I created https://github.com/microsoft/ML-For-Beginners/discussions/558 and do linguistic reviews of all the Hindi language content here so that I can close PRs after. thanks

**Comment by iamrohansingh09** [comment]
Hi, I am Rohan Singh, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue.

**Comment by iamrobin123** [comment]
I am contributor to OpenForce 2022. I would like to work on this issue

**Comment by mufa988** [comment]
Re-scan the QR code
