### ISSUE TITLE
Titles Guidelines

### ISSUE THREAD

**Issue by juanpflores** [microsoft/ML-For-Beginners#567]
**Is your feature request related to a problem? Please describe.**
While helping with the translations, I found there is a mix of different title styles. For example in Module 1 there is a mix of title capitalization and non-capitalization that provides some confusion while helping 

**Describe the solution you'd like**

1. Define a title style. 
2. Create content style guidelines for the courses.

**Describe alternatives you've considered**

**Additional context**
<img width="1050" alt="Screen Shot 2022-03-20 at 1 40 37 PM" src="https://user-images.githubusercontent.com/6200135/159185360-3d3db333-6d15-4156-b30e-cc2201f3368e.png">

**Comment by jlooper** [comment]
In general I think I tried to capitalize Machine Learning but probably there are lapses
