### ISSUE TITLE
outdated link in 1-Introduction/4-techniques-of-ML/README.md

### ISSUE THREAD

**Issue by zimmy87** [microsoft/ML-For-Beginners#574]
**Describe the bug**
There is a link to a slide deck [here](https://www2.cisl.ucar.edu/sites/default/files/0900%20June%2024%20Haupt_0.pdf) that points to a resource that has been move. This link is on [this page](https://github.com/microsoft/ML-For-Beginners/blob/main/1-Introduction/4-techniques-of-ML/README.md) under the "What question to ask" header

**To Reproduce**
1. Go to [this page](https://github.com/microsoft/ML-For-Beginners/blob/main/1-Introduction/4-techniques-of-ML/README.md)
2. Click on link to this [slide deck](https://www2.cisl.ucar.edu/sites/default/files/0900%20June%2024%20Haupt_0.pdf)

**Expected behavior**
Link opened to a pdf file

**Screenshots**
Link opened to a page saying the resource has been moved:

![image](https://user-images.githubusercontent.com/5205889/163039410-eec01932-b47f-4c33-bc4c-50eaab468af6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 100.0.1185.29 (Official build) (64-bit)

**Comment by jlooper** [comment]
thanks, I updated it! https://www2.cisl.ucar.edu/sites/default/files/2021-10/0900%20June%2024%20Haupt_0.pdf
