### ISSUE TITLE
Shall I add DBSCAN and Hierarchical Clustering Algo?

### ISSUE THREAD

**Issue by vedantbahel** [microsoft/ML-For-Beginners#595]
**Is your feature request related to a problem? Please describe.**
Shall I add more clustering algorithms like DBSCAN and Hierarchical clustering to this repo?

**Describe the solution you'd like**
Often data scientist try and test various algorithms to compare and analyze their performance, finalizing one and  move it to production. Currently, in this repo there is only one clustering algorithm i.e. K-means. Shall I add more clustering algorithms to this repo which are popular used?

**Comment by jlooper** [comment]
It's not a bad idea, perhaps as an appendix, if they can be done using Scikit-Learn. What do you think?

**Comment by vedantbahel** [comment]
By appendix, do you mean adding brief information and not complete
implementation. Like a guideline of implementation instead of actual
implementation.

Yes, they can be done using sklearn.
https://scikit-learn.org/stable/modules/clustering.html

Let me know, what you think.
