### ISSUE TITLE
Time requirements?

### ISSUE THREAD

**Issue by alexdresko** [microsoft/ML-For-Beginners#72]
The course is described as being "12 weeks, 24 lessons", but it doesn't give an idea as to how much time is required to complete each lesson. 

I'd like to do the course, but I need to figure out if I've got time in my current schedule.

**Comment by jlooper** [comment]
hi, good question! You should treat the lessons as a virtual lecture room - so a professor would lecture for about an hour (equivalent to reading the lecture and doing two in-class quizzes) and then you'd do homework (knowledge checks/assignments/challenges) - those probably take about one to two hours per lesson. I'd suggest walking through the 4 introductory lessons and seeing how they go. You can use the discussion board as well to track your time!
