### ISSUE TITLE
Tribute to Contributors in diffrent way 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [microsoft/ML-For-Beginners#90]
**Is your feature request related to a problem? Please describe.**
As of now, we are Thanking Contributors like this 👇🏻 
<hr>

![image](https://user-images.githubusercontent.com/76584243/124394509-6a2c2480-dd1d-11eb-8751-bcd87c7de07a.png)

<hr>

I think we can do it in a more better and personalized way ! 

**Describe the solution you'd like**

We can shift this section at bottom of reading me the file and we can add everyone's card so If anyone wants to reach out to them they can visit their GitHub profile card will contain their GitHub avatar and name where the link will be added.

**Describe alternatives you've considered**
Or we can just add links to their profiles to the existing places this will also help but the card will look a more attractive and a small tribute to great people!! 

Will like to add this feature

**Comment by seryozni** [comment]
I think it would be nice to add not only @nickname, but also real name and surname (for those, who'd like to share, of course) of contributors :)

**Comment by jlooper** [comment]
That section is thanks to authors; contributors are thanked elsewhere
