### ISSUE TITLE
Issue in README

### ISSUE THREAD

**Issue by kkanekii** [microsoft/ML-For-Beginners#95]
Issue in the markdown, says no repo found on android etc...
File attached:  [screenshot.png](https://user-images.githubusercontent.com/86641210/124445470-355fb200-dd9d-11eb-80b4-e63758b58ba3.png)

**Comment by jlooper** [comment]
I noticed this, it’s weird as the markdown seems correct. Let’s investigate

**Comment by kkanekii** [comment]
yeah sure

**Comment by kkanekii** [comment]
It now does give numbers but definitely not even close ones

**Comment by jlooper** [comment]
This was a private repo for a while, that might affect it?

**Comment by kkanekii** [comment]
I really dont think so, I went through the README code, and it seems to be perfect, I'm really new to markdowns and github so I really wouldn't have the slightest clue

**Comment by Rishit-dagli** [comment]
I think the current badge uses the following URL:

```
https://img.shields.io/github/watchers/microsoft/ML-For-Beginners.svg?style=social&label=Watch&maxAge=2592000
```

We have the `maxAge` parameter (https://github.com/readthedocs/readthedocs.org/pull/3005) and GitHub has an earlier cche of this image. An easy way to fix this might be to simply use [this URL](https://img.shields.io/github/watchers/microsoft/ML-For-Beginners.svg?style=social&label=Watch) which renders correctly:

```
https://img.shields.io/github/watchers/microsoft/ML-For-Beginners.svg?style=social&label=Watch
```

**Comment by kkanekii** [comment]
I'll do the needful in a bit, thank you!

**Comment by jlooper** [comment]
> I'll do the needful in a bit, thank you!

I think Rishit sorted it, thanks all!
